theme: jekyll-theme-cayman
title: Higgsino Physics
description: Simple animated explanations of fun physics!
google_analytics: G-DT901SRLT6
collections:
    nfts:
        output: true
    articles:
        output: true
permalink: /:categories/:title/
